[package]
name = "async-openai-wasm-macros"
version = "0.1.0"
authors = [
    "Contributors of the async-openai crate",
    "ifsheldon <async_openai_wasm@reify.ing>"
]
keywords = ["openai", "macros", "ai"]
description = "Macros for async-openai-wasm"
edition = "2024"
license = "MIT"
homepage = "https://github.com/ifsheldon/async-openai-wasm"
repository = "https://github.com/ifsheldon/async-openai-wasm"
rust-version = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"